services:
  web:
    build: .
    container_name: web
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "8010:8010"
    labels:
      - "traefik.http.routers.web.rule=Host(`new.oscarprince.ch`)"
      - "traefik.http.services.web.loadbalancer.server.port=8010"
  api:
    build: ./pocketbase/.
    container_name: oscarprince-api
    restart: unless-stopped
    ports:
      - "8011:8011"
    volumes:
      - /data:/pb_data

networks:
  proxy:
    name: proxy
    external: true