services:
  web:
    build: .
    container_name: ssr-oscarprince-web
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "4000:4000"
    labels:
      - "traefik.http.routers.ssr-oscarprince-web-http.rule=Host(`ssr.oscarprince.ch`)"
      - "traefik.http.routers.ssr-oscarprince-web-http.middlewares=ssr-oscarprince-web-https"
      - "traefik.http.middlewares.ssr-oscarprince-web-https.redirectscheme.scheme=https"
      - "traefik.http.routers.ssr-oscarprince-web-http.entrypoints=web"
      - "traefik.http.routers.ssr-oscarprince-web.rule=Host(`ssr.oscarprince.ch`)"
      - "traefik.http.services.ssr-oscarprince-web.loadbalancer.server.port=4000"
      - "traefik.http.routers.ssr-oscarprince-web.entrypoints=websecure"
      - "traefik.http.routers.ssr-oscarprince-web.tls.certresolver=zeusresolver"
      - "traefik.http.routers.ssr-oscarprince-web.tls=true"

networks:
  proxy:
    name: proxy
    external: true