services:
  web:
    build: .
    container_name: oscarprince-web
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "8010:8010"
    labels:
      - "traefik.http.routers.oscarprince-web-http.rule=Host(`new.oscarprince.ch`)"
      - "traefik.http.routers.oscarprince-web-http.middlewares=oscarprince-web-https"
      - "traefik.http.middlewares.oscarprince-web-https.redirectscheme.scheme=https"
      - "traefik.http.routers.oscarprince-web-http.entrypoints=web"
      - "traefik.http.routers.oscarprince-web.rule=Host(`new.oscarprince.ch`)"
      - "traefik.http.services.oscarprince-web.loadbalancer.server.port=8010"
      - "traefik.http.routers.oscarprince-web.entrypoints=websecure"
      - "traefik.http.routers.oscarprince-web.tls.certresolver=zeusresolver"
      - "traefik.http.routers.oscarprince-web.tls=true"
  api:
    build: ./pocketbase/.
    container_name: oscarprince-api
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "8011:8011"
    volumes:
      - pb_data:/pb_data
    labels:
      - "traefik.http.routers.oscarprince-api-http.rule=Host(`api.new.oscarprince.ch`)"
      - "traefik.http.routers.oscarprince-api-http.middlewares=oscarprince-api-https"
      - "traefik.http.middlewares.oscarprince-api-https.redirectscheme.scheme=https"
      - "traefik.http.routers.oscarprince-api-http.entrypoints=web"
      - "traefik.http.routers.oscarprince-api.rule=Host(`api.new.oscarprince.ch`)"
      - "traefik.http.services.oscarprince-api.loadbalancer.server.port=8011"
      - "traefik.http.routers.oscarprince-api.entrypoints=websecure"
      - "traefik.http.routers.oscarprince-api.tls.certresolver=zeusresolver"
      - "traefik.http.routers.oscarprince-api.tls=true"

networks:
  proxy:
    name: proxy
    external: true

volumes:
  pb_data: