# fly.toml app configuration file generated for oscarprinceweb on 2023-08-08T05:46:19Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "oscarprinceweb"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
